# Generated by Django 5.2.2 on 2025-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the chat session.",
                        max_length=255,
                    ),
                ),
                (
                    "user_message",
                    models.TextField(help_text="The message sent by the user."),
                ),
                (
                    "bot_response",
                    models.TextField(
                        help_text="The response generated by the chatbot."
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time of the interaction."
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Interaction",
                "verbose_name_plural": "Chat Interactions",
                "ordering": ["timestamp"],
            },
        ),
    ]
